export const buildExplorerUrl = (
  chain: string,
  type: 'tx' | 'address' | 'block' | 'token',
  hash: string,
): string | undefined => {
  const chainKey = chain.trim().toLowerCase();

  const baseChainMap: Record<string, string> = {
    abstract: 'https://abscan.org',
    monad: 'https://mainnet-beta.monvision.io',
    'monad testnet': 'https://explorer.monad-testnet.category.xyz',
    plume: 'https://explorer.plumenetwork.xyz',
    alephium: 'https://explorer.alephium.org',
    arbitrum: 'https://arbiscan.io',
    'arbitrum nova': 'https://nova.arbiscan.io',
    'arbitrum sepolia testnet': 'https://sepolia.arbiscan.io',
    arthera: 'https://explorer.arthera.net',
    'arthera testnet': 'https://explorer-test.arthera.net',
    astar: 'https://astar.subscan.io',
    aurora: 'https://explorer.aurora.dev',
    'avalanche c-chain': 'https://snowtrace.io',
    bahamut: 'https://www.ftnscan.com',
    base: 'https://basescan.org',
    'berachain bartio': 'https://artio.beratrail.io',
    berachain: 'https://beratrail.io',
    'bittorrent chain': 'https://bttcscan.com',
    blast: 'https://blastscan.io',
    'bnb smart chain (bep20)': 'https://bscscan.com',
    boba: 'https://bobascan.com',
    canto: 'https://cantoscan.com',
    celestia: 'https://celenium.io',
    'celo alfajores testnet': 'https://alfajores.celoscan.io',
    celo: 'https://explorer.celo.org/mainnet',
    conflux: 'https://evm.confluxscan.net',
    cronos: 'https://cronoscan.com',
    degen: 'https://explorer.degen.tips',
    'dfk subnet': 'https://subnets.avax.network/defi-kingdoms',
    ethereum: 'https://etherscan.io',
    'ethereum sepolia testnet': 'https://sepolia.etherscan.io',
    eos: 'https://explorer.evm.eosnetwork.com',
    fantom: 'https://ftmscan.com',
    graphlinq: 'https://explorer.graphlinq.io',
    harmony: 'https://explorer.harmony.one',
    heco: 'https://www.hecoinfo.com',
    hedera: 'https://hashscan.io/mainnet',
    ink: 'https://explorer.inkonchain.com',
    'immutable zkevm': 'https://explorer.immutable.com',
    klaytn: 'https://scope.klaytn.com',
    kucoin: 'https://explorer.kcc.io',
    linea: 'https://lineascan.build',
    manta: 'https://pacific-explorer.manta.network',
    mantle: 'https://explorer.mantle.xyz',
    matchain: 'https://www.matchscan.io',
    mode: 'https://explorer.mode.network',
    metis: 'https://andromeda-explorer.metis.io',
    moonbeam: 'https://moonscan.io',
    'mega testnet': 'https://megaexplorer.xyz',
    moonriver: 'https://moonriver.moonscan.io',
    oasis: 'https://explorer.emerald.oasis.dev',
    'oasis sapphire': 'https://explorer.sapphire.oasis.io',
    okex: 'https://www.oklink.com/xlayer',
    optimistic: 'https://optimistic.etherscan.io',
    polygon: 'https://polygonscan.com',
    'polygon zkevm': 'https://zkevm.polygonscan.com',
    scroll: 'https://blockscout.scroll.io',
    'secret network': 'https://www.mintscan.io/secret',
    shibarium: 'https://www.shibariumscan.io',
    'shimmer evm': 'https://explorer.evm.shimmer.network',
    smartbch: 'https://sonar.cash',
    solana: 'https://solscan.io',
    starknet: 'https://starkscan.co',
    sonic: 'https://sonicscan.org',
    sui: 'https://suiscan.xyz/mainnet',
    supra: 'https://suprascan.io',
    'supra testnet': 'https://testnet.suprascan.io',
    'vanar vanguard testnet': 'https://explorer-vanguard.vanarchain.com',
    vanar: 'https://explorer.vanarchain.com',
    velas: 'https://evmexplorer.velas.com',
    wemix: 'https://explorer.wemix.com',
    xdai: 'https://gnosisscan.io',
    zetachain: 'https://zetachain.blockscout.com',
    'zklink nova': 'https://explorer.zklink.io',
    zksync: 'https://zksync2-mainnet.zkscan.io',
    zora: 'https://explorer.zora.energy',
    merlin: 'https://scan.merlinchain.io',
    taiko: '\thttps://taikoscan.io',
    sei: 'https://seistream.app',
    hyperevm: 'https://purrsec.com',
    'hyperevm testnet': 'https://testnet.purrsec.com',
    botanix: 'https://botanixscan.io',
    'x layer': 'https://web3.okx.com/explorer/x-layer',
    story: 'https://www.storyscan.io',
    plasma: 'https://plasmascan.to',
    bob: 'https://explorer.gobob.xyz',
  };

  const baseChainIdMap: Record<string, string> = {
    'evm:2741': 'https://abscan.org',
    'evm:143': 'https://mainnet-beta.monvision.io',
    'evm:10143': 'https://explorer.monad-testnet.category.xyz',
    'evm:98866': 'https://explorer.plumenetwork.xyz',
    'alephium:0': 'https://explorer.alephium.org',
    'evm:42161': 'https://arbiscan.io',
    'evm:42170': 'https://nova.arbiscan.io',
    'evm:421614': 'https://sepolia.arbiscan.io',
    'evm:10242': 'https://explorer.arthera.net',
    'evm:10243': 'https://explorer-test.arthera.net',
    'evm:592': 'https://astar.subscan.io',
    'evm:1313161554': 'https://explorer.aurora.dev',
    'evm:43114': 'https://snowtrace.io',
    'evm:5165': 'https://www.ftnscan.com',
    'evm:8453': 'https://basescan.org',
    'evm:80084': 'https://artio.beratrail.io',
    'evm:80094': 'https://beratrail.io',
    'evm:199': 'https://bttcscan.com',
    'evm:81457': 'https://blastscan.io',
    'evm:56': 'https://bscscan.com',
    'evm:288': 'https://bobascan.com',
    'evm:7700': 'https://cantoscan.com',
    'cosmos:mocha-4': 'https://celenium.io',
    'evm:44787': 'https://alfajores.celoscan.io',
    'evm:42220': 'https://explorer.celo.org/mainnet',
    'evm:1030': 'https://evm.confluxscan.net',
    'evm:25': 'https://cronoscan.com',
    'evm:666666666': 'https://explorer.degen.tips',
    'evm:53935': 'https://subnets.avax.network/defi-kingdoms',
    'evm:1': 'https://etherscan.io',
    'evm:11155111': 'https://sepolia.etherscan.io',
    'evm:17777': 'https://explorer.evm.eosnetwork.com',
    'evm:250': 'https://ftmscan.com',
    'evm:614': 'https://explorer.graphlinq.io',
    'evm:1666600000': 'https://explorer.harmony.one',
    'evm:128': 'https://www.hecoinfo.com',
    'evm:295': 'https://hashscan.io/mainnet',
    'evm:57073': 'https://explorer.inkonchain.com',
    'evm:13371': 'https://explorer.immutable.com',
    'evm:8217': 'https://scope.klaytn.com',
    'evm:321': 'https://explorer.kcc.io',
    'evm:59144': 'https://lineascan.build',
    'evm:169': 'https://pacific-explorer.manta.network',
    'evm:5000': 'https://explorer.mantle.xyz',
    'evm:698': 'https://www.matchscan.io',
    'evm:34443': 'https://explorer.mode.network',
    'evm:1088': 'https://andromeda-explorer.metis.io',
    'evm:1284': 'https://moonscan.io',
    'evm:6342': 'https://megaexplorer.xyz',
    'evm:1285': 'https://moonriver.moonscan.io',
    'evm:42262': 'https://explorer.emerald.oasis.dev',
    'evm:23294': 'https://explorer.sapphire.oasis.io',
    'evm:66': 'https://www.oklink.com/xlayer',
    'evm:10': 'https://optimistic.etherscan.io',
    'evm:137': 'https://polygonscan.com',
    'evm:1101': 'https://zkevm.polygonscan.com',
    'evm:534352': 'https://blockscout.scroll.io',
    'secret:4': 'https://www.mintscan.io/secret',
    'evm:109': 'https://www.shibariumscan.io',
    'evm:148': 'https://explorer.evm.shimmer.network',
    'evm:10000': 'https://sonar.cash',
    'solana:solana': 'https://solscan.io',
    'starknet:starknet': 'https://starkscan.co',
    'evm:146': 'https://sonicscan.org',
    'sui:sui': 'https://suiscan.xyz/mainnet',
    'supra:8': 'https://suprascan.io',
    'supra:6': 'https://testnet.suprascan.io',
    'evm:78600': 'https://explorer-vanguard.vanarchain.com',
    'evm:2040': 'https://explorer.vanarchain.com',
    'evm:106': 'https://evmexplorer.velas.com',
    'evm:1111': 'https://explorer.wemix.com',
    'evm:100': 'https://gnosisscan.io',
    'evm:7000': 'https://zetachain.blockscout.com',
    'evm:810180': 'https://explorer.zklink.io',
    'evm:324': 'https://zksync2-mainnet.zkscan.io',
    'evm:7777777': 'https://explorer.zora.energy',
    'evm:4200': 'https://scan.merlinchain.io',
    'evm:167000': '\thttps://taikoscan.io',
    'evm:1329': 'https://seistream.app',
    'evm:999': 'https://purrsec.com',
    'evm:998': 'https://testnet.purrsec.com',
    'evm:3637': 'https://botanixscan.io',
    'evm:196': 'https://web3.okx.com/explorer/x-layer',
    'evm:1514': 'https://www.storyscan.io',
    'evm:9745': 'https://plasmascan.to',
    'evm:60808': 'https://explorer.gobob.xyz',
  };

  let base = baseChainMap[chainKey] || baseChainIdMap[chainKey] || undefined;

  if (!base) return undefined;

  // Clean up spaces, tabs, trailing slashes
  base = base.replace(/\s+/g, '').replace(/\/+$/, '');

  const defaultPaths = {
    tx: `${base}/tx/${hash}`,
    address: `${base}/address/${hash}`,
    block: `${base}/block/${hash}`,
    token: `${base}/token/${hash}`,
  };

  switch (chainKey) {
    case 'solana':
      return {
        tx: `${base}/tx/${hash}`,
        address: `${base}/account/${hash}`,
        block: `${base}/block/${hash}`,
        token: `${base}/token/${hash}`,
      }[type];

    case 'aptos':
      return {
        tx: `${base}/txn/${hash}`,
        address: `${base}/account/${hash}`,
        block: `${base}/block/${hash}`,
        token: `${base}/token/${hash}`,
      }[type];

    case 'sui':
      return {
        tx: `${base}/txblock/${hash}`,
        address: `${base}/object/${hash}`,
        block: `${base}/checkpoint/${hash}`,
        token: `${base}/object/${hash}`,
      }[type];

    case 'ton':
      return {
        tx: `${base}/transaction/${hash}`,
        address: `${base}/address/${hash}`,
        block: `${base}/block/${hash}`,
        token: `${base}/jetton/${hash}`,
      }[type];

    default:
      return defaultPaths[type];
  }
};
